### ISSUE TITLE
TODOMVC still fails on Safari 

### ISSUE THREAD

**Issue by LeanderK** [tweag/asterius#837]
**Describe the bug**
Last time I tried asters (#401), starting it was impossible due to the lack of BigInt. This this seems like it was recently solved (https://caniuse.com/bigint). I am currently on 14.0, which should have BigInt support, but I still can't run TODOMVC:

`[Error] Failed to load resource: the server responded with a status of 404 () (learn.json, line 0)
[Error] TypeError: WebAssembly.compileStreaming is not a function. (In 'WebAssembly.compileStreaming(fetch("todomvc.wasm"))', 'WebAssembly.compileStreaming' is undefined)
	(anonymous function) (todomvc.js:1:1014)
	Global Code (todomvc.js:1:1024)`

**To Reproduce**
open the TODOMVC on safari >= 14.0

**Expected behavior**
It should work 

**Environment**
 - OS name + version: MacOs 10.14.6 (18G6032)
 - Version of the code:

**Additional context**

**Comment by typedrat** [comment]
[This is being fixed upstream.](https://bugs.webkit.org/show_bug.cgi?id=173105)

**Comment by LeanderK** [comment]
There's a recent interaction on the ticket! Sounds too good to be true, so it might just work in a few weeks!

**Comment by typedrat** [comment]
It's merged, so it's just a matter of waiting for the version of WebKit in Safari to crank.

**Comment by typedrat** [comment]
Someone should check with [Safari TP 121 or higher](https://webkit.org/blog/11555/release-notes-for-safari-technology-preview-121/). It should work, or at least find the next issue.

**Comment by ak3n** [comment]
I have just checked and it works in "Release 123 (Safari 14.2, WebKit 15612.1.7.10)".
